name: which

on:
  workflow_dispatch:

jobs:
  list-videos:
    name: whichi
    runs-on: ubuntu-latest
    steps:
      - name: which1
        run: |
          which python3
      - name: which2
        run: |
          which jq
      - name: ffmpeg
        run: |
          sudo apt-get update
          sudo apt install ffmpeg
          ffmpeg -filters | grep rubberband
      - name: Upload FFmpeg with rubberband to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ffmpeg-rb-v1
          files: ffmpeg-rubberband.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

