name: which

on:
  workflow_dispatch:

jobs:
  list-videos:
    name: whichi
    runs-on: ubuntu-latest
    steps:
      - name: which1
        run: |
          which python3
      - name: which2
        run: |
          which jq
      - name: which4
        run: |
          ffmpeg -filters | grep rubberband
